name 'proteon-maven'
version '1.0.1'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/proteon/puppet-maven'
source 'http://github.com/proteon/puppet-maven'
summary 'Apache Maven module for Puppet'
description 'A Puppet module to download artifacts from Maven repositories'
dependency 'maestrodev/wget', '>=0.0.1'
